### ISSUE TITLE
script for ethscan, matic 

### ISSUE THREAD

**Issue by solomon47** [samugi/bsc_newcoin_finder#3]
Bsc has 99.99% scams so its getting harder to find good projects on it. is it possible to configure the code for other blockchains?

**Comment by samugi** [comment]
Thanks for opening this issue.

While that is a point worth considering, it would be probably best starting a whole new project for that purpose considered there would be basically no code reuse from this script, due to the different sources of data. 

Good as an idea for the future but I'm going to close it as _won't do_ (which means it won't be implemented in **this** script specifically).
